server:
  port: 9090
  ip: localhost
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/management_system?serveTimezone=GMT%2b8  # GMT+8 GMT就是格林威治标准时间 +8 就是中国的时间
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 200MB     # 文件上传大小限制为
      max-request-size: 200MB  # 请求大小限制为
  redis:
    port: 6379
    host: localhost
  mail:
    protocol: smtps
    #    protocol: smtp
    # 配置 SMTP 服务器地址
    #   host: smtp.qq.com
    host: smtp.163.com
    # 发送者邮箱
    username: mengyuchao2001@163.com
      #    username: mengyuchaotide@gmail.com
      #   from: mengyuchaotide@gmail.com直接配这个不用传
      #username: 1904246005@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: HZBEYMIFJUPFZTOG
      # 端口号465或587
    port: 465
      #port: 587
      # 默认的邮件编码为UTF-8
    default-encoding: UTF-8


  #mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml 不用这个，用configuration的形式
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: E:\Users\Desktop\backstageManagementSystem\temp\files\
#    path: /home/files


#调整日志级别
logging:
  level:
    com.yuchao: trace #指定包的日志级别
  file:
    path: springbootlog #没指定具体路径在当前项目下生成